### ISSUE TITLE
Não existe teste no template

### ISSUE THREAD

**Issue by sudo-victor** [rocketseat-education/ignite-template-react-native-stream-data#1]
Notei que a rocketseat usa testes para validar o código porém nesse template não existe os testes. Proposital?

**Comment by vinifraga** [comment]
Fala @sudo-victor, desculpe a demora.

Para um atendimento mais rápido, pedimos que fale conosco pelo fórum :pray:

Sim, esse desafio não possui testes propositalmente. A ideia é que cada vez menos utilizemos testes automatizados, porque limita muito a liberdade (e criatividade) de vocês nos desafios.

Espero ter ajudado :purple_heart:
