### ISSUE TITLE
Error no uso do Feather e Fontisto

### ISSUE THREAD

**Issue by rafaeld3v** [rocketseat-education/ignite-template-react-native-stream-data#2]
Ao implementar os icones na aplicação retorna o seguinte error.

Error message:
'Feather' cannot be used as a JSX component.
  Its instance type 'Component<IconProps<"type" | "code" | "link" | "map" | "menu" | "video" | "circle" | "filter" | "image" | "key" | "search" | "radio" | "repeat" | "anchor" | "bold" | "target" | "x" | "grid" | "list" | ... 266 more ... | "zoom-out">, {}, any>' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("C:/Users/rafae/Desktop/ignite-react-native-stream-data/node_modules/@types/react-native/node_modules/@types/react/index").ReactNode'.

Error message: 
'Fontisto' cannot be used as a JSX component.
  Its instance type 'Component<IconProps<"code" | "link" | "map" | "picture" | "ruby" | "ellipse" | "filter" | "line" | "stop" | "key" | "search" | "anchor" | "bold" | "at" | "cursor" | "origin" | "email" | "download" | ... 598 more ... | "rectangle">, {}, any>' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("C:/Users/rafae/Desktop/ignite-react-native-stream-data/node_modules/@types/react-native/node_modules/@types/react/index").ReactNode'.

Link do repositori: https://github.com/RafaelD3v/ignite-react-native-stream-data

**Comment by vinifraga** [comment]
Fala @rafaeld3v , desculpe a demora.

Para um atendimento mais rápido, pedimos que fale conosco pelo fórum :pray: 

Esse erro é por conta da confusão de tipagens do React e React Native nas últimas versões, com o `commit` do upgrade da SDK para 45 eu realizei o `fix` dessa questão.

Espero ter ajudado
